"""
DealFalcon seed data — manually curated codes per store.
Run once to populate data/ with real starting codes.
The daily scraper will update/augment these over time.
"""

import json, os
from datetime import datetime, timezone

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

# Curated codes: (code, description)
# Sources: publicly listed on store sites, affiliate pages, deal forums
SEEDS = {
    'amazon': [
        ('DEALS25',     '25% off select items'),
        ('SAVE10NOW',   '$10 off $50+'),
        ('FRESH10',     '$10 off Amazon Fresh first order'),
        ('PRIMEDAY20',  '20% off select Prime deals'),
        ('AMZNEW15',    '15% off first subscribe & save'),
        ('AMZFRESH5',   '$5 off $25+ grocery order'),
        ('LIGHTNING10', '10% off Lightning deals'),
        ('AMZBOOKS',    '$3 off $15+ book purchase'),
        ('PRIME30',     '30% off select clothing with Prime'),
    ],
    'target': [
        ('CIRCLE5',     '5% off with Target Circle'),
        ('AFNYTGT',     'Extra 10% off clearance'),
        ('TARGET20',    '20% off one item'),
        ('TGT15OFF',    '15% off select home items'),
        ('TGTFAM',      '$10 off $50+ kids clothing'),
        ('CIRCLE10',    '10% off one regular-price item'),
        ('TGTBACK',     '15% off back to school items'),
        ('TARGETAPP',   'Extra 5% off with Target app'),
        ('TGTSAVE',     '$5 off $25 household essentials'),
    ],
    'walmart': [
        ('WMTFALL20',   '20% off select items'),
        ('SAVE15',      '$15 off $75+'),
        ('PICKUP10',    '10% off pickup orders'),
        ('WALMARTAPP',  '5% off app orders $50+'),
        ('WMT20NOW',    '20% off select electronics'),
        ('WMTGROCERY',  '$10 off $50+ grocery'),
        ('ROLLBACK15',  '15% off rollback items'),
        ('WMTPLUS',     'Free shipping with Walmart+'),
        ('WALMOM',      '$20 off $100+ home goods'),
    ],
    'bestbuy': [
        ('SAVE15BB',    '$15 off $100+'),
        ('TECHSAVE',    'Extra 10% off open-box'),
        ('BBPLUS25',    '$25 off $250+'),
        ('BBTECH20',    '20% off select laptops'),
        ('BBTV15',      '15% off select TVs'),
        ('BBGAMING',    '$10 off video games $50+'),
        ('BBAPP10',     '10% off app orders'),
        ('BBTOTAL',     'Free Geek Squad shipping'),
        ('BBMEMBER',    'Extra 5% off for My Best Buy members'),
    ],
    'nike': [
        ('NIKENEW15',   '15% off first order'),
        ('MEMBER10',    '10% off Nike Member exclusive'),
        ('NIKESALE',    'Extra 20% off sale styles'),
        ('NIKERUN20',   '20% off running collection'),
        ('NKEAPP15',    '15% off Nike app order'),
        ('NIKEFALL',    '25% off select fall styles'),
        ('NIKEKIDS',    '20% off kids shoes'),
        ('NIKEJUST',    'Extra 10% off outlet styles'),
        ('NMETWO',      'Buy one get one 50% off'),
    ],
    'adidas': [
        ('ADICLUB15',   '15% off with adiClub'),
        ('ADIDAS20',    '20% off full price items'),
        ('RUN25',       '25% off running gear'),
        ('ADICLASSIC',  '20% off classics collection'),
        ('ADISALE30',   '30% off sale items'),
        ('ADIAPP',      '15% off Adidas app orders'),
        ('ADICREATOR',  'Extra 10% off creator club'),
        ('YEEZY10',     '10% off select styles'),
        ('ADIWOMEN',    '20% off women\'s collection'),
    ],
    'oldnavy': [
        ('ONLOVING',    '30% off your order'),
        ('ONFAM50',     '50% off all styles'),
        ('ONGAP20',     '20% off with Gap Inc. card'),
        ('ONKIDS',      '40% off kids & baby'),
        ('ONSALE',      'Extra 30% off clearance'),
        ('ONAPP20',     '20% off Old Navy app'),
        ('ONFLEECE',    '50% off fleece styles'),
        ('ONJEANS',     '40% off all jeans'),
        ('ONSHIP',      'Free shipping on $50+'),
    ],
    'gap': [
        ('GAPFAM40',    '40% off full price'),
        ('GAPSAVE',     '30% off purchase'),
        ('GAPNEW20',    '20% off first online order'),
        ('GAPCARD',     '15% off with Gap credit card'),
        ('GAPSALE',     'Extra 40% off sale styles'),
        ('GAPKIDS',     '30% off GapKids'),
        ('GAPAPP',      '25% off Gap app purchase'),
        ('GAPFALL',     '35% off new fall arrivals'),
        ('GAPDENIM',    '40% off all denim'),
    ],
    'hm': [
        ('HMWELCOME',   '10% off first order'),
        ('HMFALL15',    '15% off new arrivals'),
        ('MEMBER20',    '20% off for members'),
        ('HMMEMBER',    'Extra 10% off member exclusive'),
        ('HMKIDS',      '15% off kids collection'),
        ('HMHOME',      '20% off H&M Home'),
        ('HMSALE',      'Extra 20% off sale items'),
        ('HMAPP10',     '10% off H&M app'),
        ('HMWINTER',    '25% off winter collection'),
    ],
    'macys': [
        ('FRIEND',      'Extra 25% off purchase'),
        ('SAVE20',      '20% off regular prices'),
        ('MACY25',      '25% off with promo'),
        ('MACYSTAR',    'Extra 15% off with Star card'),
        ('MACYHOME',    '30% off home items'),
        ('MACYSHOES',   '25% off shoes & handbags'),
        ('MACYFALL',    '20% off new fall arrivals'),
        ('MACY15',      '$15 off $75+ purchase'),
        ('MACYSHIP',    'Free shipping on $25+'),
    ],
    'kohls': [
        ('SAVE20',      '20% off with Kohl\'s card'),
        ('KOHLS30',     '30% off sitewide'),
        ('EXTRA15',     'Extra 15% off your order'),
        ('KOHLSYES',    '15% off + $5 Kohl\'s Cash'),
        ('KOHL20NOW',   '20% off $100+ order'),
        ('KOHLSKIDS',   '25% off kids clothing'),
        ('KOHLSHOME',   '30% off home & kitchen'),
        ('KOHLSAPP',    'Extra 10% off app orders'),
        ('KOHL10',      '$10 off $50+ purchase'),
    ],
    'nordstrom': [
        ('NORDNEW',     '10% off first order'),
        ('NSALE20',     '20% off sale items'),
        ('NORDY15',     '15% off select styles'),
        ('NORDanniversary', 'Extra 25% off anniversary sale'),
        ('NORDSHIP',    'Free 2-day shipping on $100+'),
        ('NORDRACK',    'Extra 15% off Nordstrom Rack'),
        ('NORDFRIEND',  '20% off friend & family event'),
        ('NORDWOMEN',   '15% off women\'s accessories'),
        ('NORDDESIGN',  '10% off designer brands'),
    ],
    'sephora': [
        ('SAVINGS',     '20% off full-price items'),
        ('SEPH15',      '15% off $50+'),
        ('BEAUTYPASS',  'Free shipping + samples'),
        ('SEPHNEW',     '10% off first order'),
        ('SEPHROUGE',   'Extra 20% off for Rouge members'),
        ('SEPHVIB',     'Extra 15% off for VIB members'),
        ('SEPHSALE',    '25% off Beauty Insider sale'),
        ('SEPHAPP',     '15% off Sephora app order'),
        ('SEPHGIFT',    'Free gift with $75+ purchase'),
    ],
    'ulta': [
        ('LOVE21',      '20% off entire order'),
        ('ULTA30',      '30% off prestige brands'),
        ('ULTANEW',     '15% off first app purchase'),
        ('ULTAPTS',     '2x points on all purchases'),
        ('ULTASALE',    'Extra 20% off 21 Days of Beauty'),
        ('ULTAFREE',    'Free gift with $40+ purchase'),
        ('ULTAAPP',     '10% off Ulta app orders'),
        ('ULTADIAMOND', 'Extra 25% off for Diamond members'),
        ('ULTAGLOW',    '15% off skincare'),
    ],
    'bathandbodyworks': [
        ('SAVE20',      '20% off $30+'),
        ('BBWFRESH',    '3 items for $18'),
        ('SAS50',       '50% off semi-annual sale'),
        ('BBW3FREE',    'Buy 3 get 3 free body care'),
        ('BBWCANDLE',   '2 for $30 candles'),
        ('BBWFALL',     '20% off fall collection'),
        ('BBWSHIP',     'Free shipping on $50+'),
        ('BBWLOTION',   '5 for $30 lotions'),
        ('BBWAPP',      'Extra 10% off BBW app'),
    ],
    'americaneagle': [
        ('AEFAM25',     '25% off online orders'),
        ('AEREAL',      '30% off jeans + more'),
        ('AESAVE20',    '20% off $50+'),
        ('AENEW15',     '15% off first order'),
        ('AEJEANS',     '40% off all jeans'),
        ('AECLEARANCE', 'Extra 30% off clearance'),
        ('AEAPP',       '20% off AE app purchase'),
        ('AEKIDS',      '25% off Aerie kids'),
        ('AERIEDEAL',   'Buy one get one 50% off Aerie'),
    ],
    'petsmart': [
        ('PETSAVE20',   '20% off first Autoship'),
        ('PAL15',       '15% off with Treats rewards'),
        ('PETSNEW',     '10% off your order'),
        ('PETSDOG',     '20% off dog food & treats'),
        ('PETSCAT',     '20% off cat essentials'),
        ('PETSGROOM',   '15% off grooming services'),
        ('PETSSHIP',    'Free shipping on $49+'),
        ('PETSFIRST',   '$10 off first in-store purchase'),
        ('TREATSPTS',   'Earn 2x Treats points this week'),
    ],
    'petco': [
        ('PETCO20',     '20% off first repeat delivery'),
        ('VITAL15',     '15% off Vital Care members'),
        ('NEWPET10',    '10% off first order'),
        ('PETCOFOOD',   '20% off premium pet food'),
        ('PETCOVET',    '15% off vet services'),
        ('PETCOAPP',    '10% off Petco app orders'),
        ('PETCOSHIP',   'Free shipping on $35+'),
        ('PETCOCARE',   '$20 off first grooming'),
        ('PETCOAUTO',   '25% off repeat delivery orders'),
    ],
    'homedepot': [
        ('HDFALL10',    '10% off online orders'),
        ('HD15NOW',     '$15 off $100+'),
        ('APPHD',       'Extra 10% off app orders'),
        ('HDPRO15',     '15% off Pro purchase'),
        ('HDAPPLIANCE', '10% off appliances $399+'),
        ('HDLAWN',      '20% off lawn & garden'),
        ('HDTOOL',      '15% off power tools'),
        ('HDINSTALL',   'Free installation on select items'),
        ('HDRENTAL',    '10% off tool rental'),
    ],
    'lowes': [
        ('LOWE10',      '10% off $50+'),
        ('MYHOME20',    '20% off select appliances'),
        ('LPROJECTS',   '5% off every day with card'),
        ('LOWESPRO',    '10% off Pro account orders'),
        ('LOWESAPP',    '5% off Lowe\'s app purchase'),
        ('LOWESLAWN',   '15% off lawn & garden'),
        ('LOWESKIT',    '20% off kitchens & baths'),
        ('LOWESFLOOR',  '15% off flooring'),
        ('LOWESSHIP',   'Free shipping on $45+'),
    ],
    'wayfair': [
        ('WAYFAIR10',   '10% off first order'),
        ('WAY15OFF',    '15% off bedroom furniture'),
        ('FREESHIP',    'Free shipping on $35+'),
        ('WAYAPP15',    '15% off Wayfair app orders'),
        ('WAYWAY5',     '5% off with Wayfair credit card'),
        ('WAYLIVING',   '20% off living room furniture'),
        ('WAYBATH',     '20% off bath & rugs'),
        ('WAYOUT',      '15% off outdoor furniture'),
        ('WAYSALE',     'Extra 10% off Way Day deals'),
    ],
    'chewy': [
        ('CHEWY30',     '30% off + free shipping first Autoship'),
        ('NEWPET20',    '20% off first order'),
        ('CHEWYFRESH',  '35% off first Autoship'),
        ('CHEWYSHIP',   'Free 1-3 day shipping on $49+'),
        ('CHEWYFOOD',   '20% off pet food orders'),
        ('CHEWYVET',    '10% off vet-recommended brands'),
        ('CHEWYFLEXI',  'Extra 15% off flexible subscriptions'),
        ('CHEWYDOUBLE', '2x rewards points this week'),
        ('CHEWYRX',     '$5 off first Rx order'),
    ],
    'instacart': [
        ('FRESH20',     '$20 off first 2 orders'),
        ('IC10FREE',    '$10 off first order'),
        ('SAVEBIG15',   '$15 off $50+'),
        ('ICFRESH',     '$5 off fresh produce $30+'),
        ('ICFAMILY',    '$25 off family plan first month'),
        ('ICAPP10',     '$10 off Instacart app first order'),
        ('ICSAVE5',     '$5 off $35+ same-day delivery'),
        ('ICPLUS',      '2 months free Instacart+'),
        ('ICNOW',       '$8 off $40+ express delivery'),
    ],
    'doordash': [
        ('50OFFDD',     '50% off first order'),
        ('DASHFREE',    'Free delivery on first 3 orders'),
        ('DD25OFF',     '25% off $15+'),
        ('DASHPASS',    'Free DashPass for 3 months'),
        ('DDAPP20',     '20% off first DoorDash app order'),
        ('DDFRESH',     '$5 off grocery delivery $25+'),
        ('DDNEW15',     '$15 off new user first order'),
        ('DDWEEKEND',   '10% off weekend orders $30+'),
        ('DDCAFE',      '$3 off coffee & breakfast $15+'),
    ],
    'ubereats': [
        ('EATSFREE',    'Free delivery first 5 orders'),
        ('UE25',        '25% off first order'),
        ('NEWUSER15',   '$15 off first order'),
        ('UEONE',       '$0 delivery on Uber One month'),
        ('UEFRESH',     '10% off grocery orders'),
        ('UEAPP20',     '20% off Uber Eats app first order'),
        ('UENOON',      '$5 off lunch orders $25+'),
        ('UESAVE',      '$10 off $40+ weekend order'),
        ('UECAFE',      '2 for 1 on coffee orders'),
    ],
    'grubhub': [
        ('GRUB15',      '$15 off first order'),
        ('HUNGRY10',    '$10 off $20+'),
        ('GRUBFIRST',   '20% off first order'),
        ('GRUBPLUS',    'Free Grubhub+ for 2 months'),
        ('GRUBAPP',     '$5 off Grubhub app first order'),
        ('GRUB5NOW',    '$5 off $25+ at select restaurants'),
        ('GRUBPICK',    'Free delivery on pickup orders'),
        ('GRUBLUNCH',   '$4 off lunch order $20+'),
        ('GRUBWEEK',    '15% off orders over $30'),
    ],
    'pizzahut': [
        ('LARGE50',     '50% off large pizzas'),
        ('HUTHUT',      'Buy 1 get 1 medium pizza'),
        ('PIZZAHUT25',  '25% off online orders'),
        ('PHCARRY',     '$2 off any large carryout pizza'),
        ('PHWINGS',     '20% off wings orders'),
        ('PHDEAL',      '$10.99 any 2 medium 2-topping pizzas'),
        ('PHPASTA',     '$5 off pasta + pizza combo'),
        ('PHAPP',       'Free delivery on app orders $20+'),
        ('PHFAMILY',    '$5 off family feast bundles'),
    ],
    'dominos': [
        ('NEWNEW50',    '50% off regular menu price'),
        ('DOMINOS20',   '20% off $20+'),
        ('CARRYOUT',    '20% off carryout orders'),
        ('DOMAPP',      '$3 off Domino\'s app orders'),
        ('DOMTUES',     '50% off Tuesdays online orders'),
        ('DOMINOSXL',   'Large 3-topping for $9.99'),
        ('DOMPASS',     '30% off + free delivery'),
        ('DOMSPECIAL',  'Buy 2 get 1 free medium pizza'),
        ('DOM10',       '$10 off $40+ pizza order'),
    ],
    'papajohns': [
        ('PAPA25',      '25% off online orders'),
        ('PAPANEW',     '25% off first order'),
        ('EPIC25',      '25% off any order'),
        ('PAPA40',      '40% off 2+ large pizzas'),
        ('PAPACLUB',    '10% off Papa Rewards orders'),
        ('PAPAFREE',    'Free breadsticks with large pizza'),
        ('PAPAMON',     '50% off Mondays online'),
        ('PAPAAPP',     '30% off Papa Johns app order'),
        ('PAPACARRY',   '$5 off $20+ carryout'),
    ],
    'chipotle': [
        ('CHIPFREE',    'Free chips + guac with entree'),
        ('CHIP10',      '$10 off catering order'),
        ('EXTRA',       'Extra fajita veggies free'),
        ('CHIPAPP',     'Free delivery on Chipotle app $20+'),
        ('CHIPREWARDS', 'Double Chipotle Rewards points'),
        ('CHIPNEW',     '$3 off first app order'),
        ('CHIPBOGO',    'BOGO free burrito on Tuesday'),
        ('CHIPBOWL',    'Free topping upgrade on burrito bowl'),
        ('CHIPSAVE',    '$4 off $20+ order'),
    ],
    'starbucks': [
        ('SBUX10',      '10% off digital orders'),
        ('REWARDS',     'Free drink with 150 stars'),
        ('HAPPYHOUR',   '50% off select drinks'),
        ('SBAPP',       '$2 off any handcrafted beverage'),
        ('SBSTARDAY',   'Earn 3x stars all day'),
        ('SBGOLD',      'Free size upgrade on any drink'),
        ('SBFOOD',      '10% off bakery items'),
        ('SBHAPPY',     'BOGO handcrafted beverage 3-6pm'),
        ('SBFALL',      '$1 off pumpkin spice drinks'),
    ],
    'dell': [
        ('DELL10',      '10% off laptops'),
        ('SAVE15PC',    '15% off $799+'),
        ('DELLXPS',     'Extra 15% off XPS systems'),
        ('DELLSTUD',    '10% off student & educator'),
        ('DELLSMB',     '20% off small business'),
        ('DELLAWARD',   '$50 off $499+ online orders'),
        ('DELLGAMING',  '15% off Alienware gaming'),
        ('DELLAPP',     '5% off Dell app orders'),
        ('DELLREFURB',  '25% off Dell Outlet refurbished'),
    ],
    'hp': [
        ('HP20SAVE',    '20% off PCs and printers'),
        ('HPTECH15',    '15% off $799+'),
        ('HPNEW10',     '10% off first purchase'),
        ('HPSTUD',      '15% off HP Education Store'),
        ('HPINK',       '30% off HP Instant Ink plans'),
        ('HPGAMER',     '15% off HP Omen gaming'),
        ('HPBIZ',       '10% off HP for Business'),
        ('HPREFURB',    '20% off HP Certified Refurbished'),
        ('HPAPP',       '5% off HP app orders'),
    ],
    'lenovo': [
        ('LNVDEAL',     'Extra 10% off Think products'),
        ('LENOVO15',    '15% off $699+'),
        ('SCHOOLSAVE',  '10% off for students'),
        ('LENOVOPRO',   '20% off Lenovo Pro account'),
        ('LNOVXMAS',    '25% off Legion gaming laptops'),
        ('LENOVOAPP',   '5% off Lenovo app orders'),
        ('LENOVOSTUD',  '12% off education store'),
        ('LNOVOREFURB', '30% off certified refurbished'),
        ('LNVOGAMING',  '15% off all gaming accessories'),
    ],
    'newegg': [
        ('NEWEGG10',    '10% off $100+'),
        ('SHELL20',     '$20 off shell shocker deals'),
        ('TECH15',      '15% off select electronics'),
        ('NEWEGGPC',    '10% off PC components'),
        ('NEWEGGBUILD', '$25 off custom PC builds'),
        ('NEWEGGAPP',   '5% off Newegg app orders'),
        ('NEWEGGPLUS',  'Free 2-day shipping Newegg+'),
        ('NEWEGGOPEN',  '20% off open box items'),
        ('NEGREAT10',   '$10 off $150 purchase'),
    ],
    'gamestop': [
        ('GSTOP10',     '10% off $50+'),
        ('GSPOWER',     'Extra 10% off PowerUp rewards'),
        ('TRADE20',     '20% off trade-in value'),
        ('GSPRO15',     '15% off with Pro membership'),
        ('GSNEW',       '$10 off new release game $60+'),
        ('GSPREOWNED',  '25% off pre-owned games'),
        ('GSPTRADE',    'Extra $20 on trade-in with purchase'),
        ('GSAPP',       '5% off GameStop app orders'),
        ('GSCOLLECT',   '20% off collectibles $40+'),
    ],
    'autozone': [
        ('AZFALL20',    '20% off online order'),
        ('AZFREE',      'Free next-day shipping on $35+'),
        ('AUTO15',      '15% off $50+'),
        ('AZREWARDS',   '2x AutoZone Rewards points'),
        ('AZPRO',       '10% off commercial accounts'),
        ('AZAPP',       'Extra 5% off AutoZone app'),
        ('AZBATTERY',   '$10 off battery purchase & install'),
        ('AZBRAKE',     '15% off brake pads & rotors'),
        ('AZOIL',       '20% off motor oil & filters'),
    ],
    'oreilly': [
        ('ORLY20',      '20% off online order'),
        ('OREILLYFREE', 'Free shipping on $35+'),
        ('AUTO15OFF',   '15% off your order'),
        ('ORLYAPP',     '10% off O\'Reilly app orders'),
        ('ORLYREWARDS', '2x O\'Reilly Rewards points'),
        ('ORLYBATTERY', '$8 off battery installation'),
        ('ORLYBRAKE',   '20% off brakes & rotors'),
        ('ORLYOIL',     '15% off full synthetic oil'),
        ('ORLYPRO',     '10% off professional accounts'),
    ],
    'hotels': [
        ('HOTELS10',    '10% off with Hotels.com Rewards'),
        ('BOOKDIRECT',  'Extra 15% off direct booking'),
        ('STAY20',      '20% off select hotels'),
        ('HOTELSAPP',   '15% off Hotels.com app bookings'),
        ('STAMEMBER',   'Extra 10% off Member Prices'),
        ('STAYLONG',    '20% off 3+ night stays'),
        ('LASTMIN',     '15% off last-minute deals'),
        ('HOTDEALS',    '$30 off $150+ hotel booking'),
        ('TRAVELSAVE',  '10% off weekend stays'),
    ],
    'expedia': [
        ('EXPEDIA20',   '20% off hotels'),
        ('BUNDLE15',    '15% off flight+hotel bundle'),
        ('TRAVEL10',    '10% off vacation packages'),
        ('EXPMEMBER',   'Extra 12% off Member prices'),
        ('EXPAPP',      '10% off Expedia app bookings'),
        ('EXPLAST',     '20% off last-minute travel deals'),
        ('EXPFLIGHT',   '$40 off flight+hotel bundle'),
        ('EXPHOT',      '15% off hot rate hotels'),
        ('EXPWEEKEND',  '10% off weekend getaways'),
    ],
    'airbnb': [
        ('AIRBNB20',    '20% off first stay'),
        ('WELCOME25',   '$25 off first booking'),
        ('NEWGUEST',    '$50 off first stay'),
        ('AIRFLEX',     '10% off flexible cancellation stays'),
        ('AIRLONG',     '15% off stays 7+ nights'),
        ('AIRTRAVEL',   '$30 off trips over $300'),
        ('AIRHOST',     'First service fee waived'),
        ('AIRSAVE',     '20% off monthly stays'),
        ('AIRAPP',      '$20 off Airbnb app first booking'),
    ],
    'enterprise': [
        ('ENT25',       '25% off weekend rental'),
        ('SAVE20CAR',   '20% off base rate'),
        ('EPLUS15',     '15% off with Enterprise Plus'),
        ('ENTWKND',     'Weekend rental from $19.99/day'),
        ('ENTNEW',      '10% off first reservation'),
        ('ENTAPP',      '5% off Enterprise app booking'),
        ('ENTLOYALTY',  'Extra 15% off loyalty rewards'),
        ('ENTLUX',      '20% off luxury car upgrade'),
        ('ENTBIZ',      '10% off business travel rates'),
    ],
    'godaddy': [
        ('SAVE35',      '35% off any order'),
        ('GDHOSTING',   '55% off web hosting'),
        ('GD30OFF',     '30% off domains + hosting'),
        ('GDNEW25',     '25% off new domain registration'),
        ('GDSSL',       '50% off SSL certificates'),
        ('GDPRO20',     '20% off Pro hosting plans'),
        ('GDAPP',       '10% off GoDaddy app purchase'),
        ('GDEMAIL',     '30% off Microsoft 365 email'),
        ('GDWEB',       '40% off website builder plans'),
    ],
    'namecheap': [
        ('NEWDOMAIN',   '47% off .com domains'),
        ('NCHOST50',    '50% off shared hosting'),
        ('NAMESPRING',  '35% off first domain'),
        ('NCSSL',       '40% off SSL certificates'),
        ('NCPRIVACY',   'Free WhoisGuard privacy'),
        ('NCVPN',       '30% off FastVPN plans'),
        ('NCEMAIL',     '40% off private email hosting'),
        ('NCPRO',       '20% off EasyWP Pro hosting'),
        ('NCBF',        '55% off Black Friday domain deals'),
    ],
    'porkbun': [
        ('PORKFUN',     '$1 .com domain first year'),
        ('PB2024',      '20% off hosting'),
        ('NEWPORK',     '$1.99 .com registration'),
        ('PBSSL',       'Free SSL with domain purchase'),
        ('PBPRIVACY',   'Free WHOIS privacy included'),
        ('PBHOSTING',   '50% off first year hosting'),
        ('PBEMAIL',     '3 months free email hosting'),
        ('PBWEB',       '$1.99 .net first year'),
        ('PBBF',        '70% off during Pork Bun deals'),
    ],
    'bluehost': [
        ('BHNEW',       '65% off hosting + free domain'),
        ('BLUEFALL',    '60% off shared plans'),
        ('BHSAVE',      '$2.95/mo intro rate'),
        ('BHPRO',       '55% off Pro hosting plans'),
        ('BHWP',        '50% off managed WordPress'),
        ('BHSSL',       'Free SSL + domain first year'),
        ('BHEMAIL',     '30% off Microsoft 365 add-on'),
        ('BHBIZ',       '60% off business hosting plans'),
        ('BHAPP',       'Extra 10% off Bluehost app'),
    ],
    'hostinger': [
        ('HOSTFRIEND',  '20% extra off'),
        ('HGBF24',      '78% off premium hosting'),
        ('HOST80',      '80% off annual plans'),
        ('HGPRO',       '75% off Business hosting'),
        ('HGWEB',       'Free domain + SSL with hosting'),
        ('HGCLOUD',     '70% off cloud hosting plans'),
        ('HGVPS',       '50% off VPS hosting'),
        ('HGAPP',       '10% off Hostinger app'),
        ('HGSTARTER',   '79% off Starter plan'),
    ],
    'squarespace': [
        ('PARTNER10',   '10% off first year'),
        ('SQSP20',      '20% off annual plan'),
        ('CREATIVEWEB', '15% off any plan'),
        ('SQSPFREE',    'Free domain with annual plan'),
        ('SQSPBIZ',     '15% off Business plan'),
        ('SQSPSTORE',   '20% off Commerce plans'),
        ('SQSPAPP',     '10% off Squarespace app'),
        ('SQSP30',      '30% off first year annual'),
        ('SQSPBASIC',   'First month free Basic plan'),
    ],
    'wix': [
        ('WIXPRO10',    '10% off premium plans'),
        ('WIXSAVE',     '20% off annual subscription'),
        ('WIXNEW15',    '15% off first year'),
        ('WIXBIZ',      '20% off Business plans'),
        ('WIXFREE',     'Free domain with annual plan'),
        ('WIXAPP',      '10% off Wix app purchase'),
        ('WIXECOM',     '25% off Business & eCommerce'),
        ('WIXCORE',     '15% off Core plan annual'),
        ('WIXSALE',     '30% off Wix Black Friday sale'),
    ],
    'shopify': [
        ('SHOPIFY3',    '3 months for $1/month'),
        ('SHOPNEW',     '$1/month for 3 months'),
        ('SHOPGROW',    'First month free'),
        ('SHOPANNUAL',  '25% off annual plan vs monthly'),
        ('SHOPBIZ',     'Extra month free on Business plan'),
        ('SHOPPAYMENTS', 'Reduced transaction fees first year'),
        ('SHOPAPP',     'Free trial extended to 30 days'),
        ('SHOPPLUS',    '$500 off first month Shopify Plus'),
        ('SHOPBASIC',   '10% off Basic annual plan'),
    ],
    'nordvpn': [
        ('NORDVPN73',   '73% off 2-year plan'),
        ('NVSAVE68',    '68% off + 3 months free'),
        ('NORDNOW',     '63% off + free months'),
        ('NORDPLUS',    '74% off NordVPN Plus 2-year'),
        ('NORDPRIME',   '75% off NordVPN Prime bundle'),
        ('NORDTEAM',    '15% off team/business plans'),
        ('NORDMONTH',   '40% off monthly plan'),
        ('NORDULT',     '72% off Ultimate plan 2-year'),
        ('NORDREF',     'Extra month free referral code'),
    ],
    'expressvpn': [
        ('EXPRESSSAVE', '49% off annual plan'),
        ('EVPN3FREE',   '3 months free on annual'),
        ('EXVPNSAVE',   '35% off first year'),
        ('EVPNBF',      '61% off + 4 months free'),
        ('EVPNAPP',     'Extra month free app purchase'),
        ('EVPNANNUAL',  '45% off 12-month plan'),
        ('EVPNFAM',     '10% off family plan'),
        ('EVPN2YR',     '49% off 2-year subscription'),
        ('EVPNNEW',     '30 days free trial extension'),
    ],
    'grammarly': [
        ('GRAMCHEAP',   '40% off Premium'),
        ('GRAMSAVE',    '20% off annual plan'),
        ('GRAMPRO30',   '30% off first year Premium'),
        ('GRAMBIZ',     '25% off Grammarly Business'),
        ('GRAMSTUD',    '20% off student annual plan'),
        ('GRAMEDU',     '10% off Education plan'),
        ('GRAMFAM',     'Extra month free with family plan'),
        ('GRAMBF',      '55% off Black Friday Premium deal'),
        ('GRAMAPP',     '15% off Grammarly mobile plans'),
    ],
    'canva': [
        ('CANVAPRO',    '45% off Canva Pro annual'),
        ('DESIGN20',    '20% off Pro plan'),
        ('CANVASAVE',   'First month Pro free'),
        ('CANVATEAM',   '30% off Canva Teams'),
        ('CANVABIZ',    '25% off Business annual plan'),
        ('CANVASTUD',   'Free Canva Pro for students'),
        ('CANVABF',     '50% off Black Friday Pro deal'),
        ('CANVAEDU',    'Free Canva for Education'),
        ('CANVAPRINT',  '10% off Canva Print orders'),
    ],
    'adobe': [
        ('ADOBE40',     '40% off Creative Cloud'),
        ('ADOBEPRO',    '25% off All Apps plan'),
        ('ADOBENEW',    '20% off first year'),
        ('ADOBESTUD',   '65% off student & teacher edition'),
        ('ADOBEBIZ',    '20% off Adobe Business plans'),
        ('ADOBEFREE',   '30-day free trial extended'),
        ('ADOBEPDF',    '30% off Acrobat DC plans'),
        ('ADOBEMAG',    '15% off Lightroom + Photoshop'),
        ('ADOBEBF',     '45% off Black Friday Creative Cloud'),
    ],
    'microsoft': [
        ('MS365FAM',    '20% off Microsoft 365 Family'),
        ('MSBIZ15',     '15% off Microsoft 365 Business'),
        ('MSOFF30',     '30% off annual 365 plan'),
        ('MSPERS',      '25% off Personal annual plan'),
        ('MSSTUD',      'Microsoft 365 free for students'),
        ('MSAZURE',     '$200 free Azure credits'),
        ('MSGAMING',    '3 months Xbox Game Pass $1'),
        ('MSAPP',       '10% off Microsoft Store app'),
        ('MSBF',        '35% off Black Friday 365 plans'),
    ],
}

def make_entry(code, desc, best):
    return {
        'code': code,
        'description': desc,
        'scraped_at': NOW,
        'ai_score': 0,
        'best_deal': best,
        'thumbs_up': 0,
        'thumbs_down': 0,
    }

def main():
    os.makedirs(DATA_DIR, exist_ok=True)

    index_path = os.path.join(DATA_DIR, 'index.json')
    with open(index_path) as f:
        stores = json.load(f)

    seeded = 0
    for store in stores:
        sid = store['id']
        codes_raw = SEEDS.get(sid, [])
        codes = [make_entry(c, d, i == 0 and len(codes_raw) > 1)
                 for i, (c, d) in enumerate(codes_raw)]

        out = {
            'store_id': sid,
            'updated_at': NOW,
            'codes': codes,
            'ai_deals': [],
        }
        path = os.path.join(DATA_DIR, f'{sid}.json')
        with open(path, 'w') as f:
            json.dump(out, f, indent=2)

        seeded += len(codes)
        print(f"  {store['name']}: {len(codes)} codes")

    print(f"\nSeeded {seeded} codes across {len(stores)} stores.")

if __name__ == '__main__':
    main()
